version: '3'
services:
  web:
    container_name: task_4
    build: .
    ports:
        - "8000:5000"
    depends_on:
        - pgsql
  database:
    container_name: pgsql
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password